services:
    App\Vacancy\Manager\VacancySlotManager:
        arguments:
            - '@doctrine.orm.entity_manager'
    
    App\Vacancy\Finder\VacancyFinder:
        arguments:
            - '@App\Repository\VacancyRepository'
